const CONFIG = {
  businessName: "The LVP Pros",
  tagline: "Tampa's Most Trusted Epoxy & Polyaspartic Flooring Contractor",
  phone: "",
  phoneRaw: "",
  email: "",
  city: "Tampa",
  state: "Florida",
  stateShort: "FL",
  address: "",
  licenseNumber: "",
  colors: {
    primary: "#2563EB",
    secondary: "#1C2333",
  },
  social: {
    facebook: "",
    instagram: "",
    youtube: "",
    yelp: "",
    nextdoor: "",
  },
  googleReviewsUrl: "",
  rating: "",
  reviewCount: 0,
  yearsExperience: 0,
  projectsCompleted: "0+",
  satisfactionRate: "98%",
  webhookUrl: "",
  metaPixelId: "",
  hero: {
    headline: "",
    subheadline: "",
    ctaPrimary: "Get My Free Quote",
    ctaSecondary: "See Our Floors",
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=75&fm=webp&auto=format",
  },
  services: [
    {
      slug: "epoxy-garage-floors",
      name: "Epoxy Garage Floors",
      desc: "",
      image: "https://images.unsplash.com/photo-1558618047-f4e60cef8b3e?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
    {
      slug: "polyaspartic-coatings",
      name: "Polyaspartic Coatings",
      desc: "",
      image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
    {
      slug: "metallic-epoxy",
      name: "Metallic Epoxy Floors",
      desc: "",
      image: "https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
    {
      slug: "commercial-warehouse-floors",
      name: "Commercial & Warehouse Floors",
      desc: "",
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
    {
      slug: "pool-deck-coatings",
      name: "Pool Deck Coatings",
      desc: "",
      image: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
    {
      slug: "basement-floor-coatings",
      name: "Basement Floor Coatings",
      desc: "",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=75&fm=webp&auto=format",
      longDesc: "",
      benefits: [],
      faqs: [],
    },
  ],
  maps: {
    mapEmbedUrl: "",
    mapSearchQuery: "",
    mapHeight: 420,
  },
  serviceAreas: [
  { slug: "tampa", name: "Tampa", county: "" }
],
  testimonials: [],
  processSteps: [
    { title: "Free Site Visit", desc: "We assess your concrete, test for moisture, measure the space, and give you a detailed written quote on the spot." },
    { title: "Surface Prep", desc: "Diamond grinding, crack repair, and primer application — the foundation that makes coatings last decades, not years." },
    { title: "Coating Installation", desc: "Basecoat, decorative flake or metallic layer, and a UV-stable polyaspartic topcoat applied by trained installers." },
    { title: "Final Inspection", desc: "We do a thorough walkthrough with you before we pack up. Your floor isn't done until you're completely satisfied." },
  ],
  faqs: [],
  legal: {
    privacyPolicyDate: "May 1, 2025",
    termsDate: "May 1, 2025",
  },
};
// rebuild
